#!/usr/bin/env bash
set -euo pipefail

readonly reason="${1:-scheduled}"
readonly deploy_dir="/opt/papermast"
readonly compose_file="${deploy_dir}/compose.production.yml"
readonly environment_file="${deploy_dir}/.env"
readonly backup_dir="/var/backups/papermast/mysql"
readonly retention_days=28
readonly max_backup_files=40
readonly timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
readonly final_file="${backup_dir}/papermast-${timestamp}-${reason}.sql.gz"
readonly temporary_file="${final_file}.partial"

trap 'rm -f "$temporary_file"' EXIT

install -d -m 700 "$backup_dir"

docker compose \
    --file "$compose_file" \
    --env-file "$environment_file" \
    exec --no-TTY mysql \
    sh -c 'exec mysqldump \
        --user=papermast \
        --password="$MYSQL_PASSWORD" \
        --single-transaction \
        --quick \
        --skip-lock-tables \
        --no-tablespaces \
        papermast' \
    | gzip --stdout > "$temporary_file"

gzip --test "$temporary_file"
test -s "$temporary_file"
gzip --decompress --stdout "$temporary_file" \
    | tail --lines 20 \
    | grep --quiet '^-- Dump completed on '
mv "$temporary_file" "$final_file"
chmod 600 "$final_file"

# Retain no backup past the age window, and cap the total number generated by
# scheduled jobs plus frequent deployments. Files are sorted newest-first so
# the most recent successful backups are always preserved.
find "$backup_dir" -type f -name 'papermast-*.sql.gz' -mtime "+${retention_days}" -delete
find "$backup_dir" -type f -name 'papermast-*.sql.gz' -printf '%T@ %p\0' \
    | sort --zero-terminated --numeric-sort --reverse \
    | tail --zero-terminated --lines "+$((max_backup_files + 1))" \
    | cut --zero-terminated --delimiter ' ' --fields 2- \
    | xargs --null --no-run-if-empty rm --
echo "$final_file"
